[theme]

# Primary accent for interactive elements
primaryColor = '#3498db'

# Background color for the main content area
backgroundColor = '#f7f7f7'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#ffffff'

# Color used for almost all text
textColor = '#1D2228'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"
